name = "DynamicPanel"
uuid = "f9c2d3d5-7d06-4116-9c95-97ecd2747305"
authors = ["Raymond Chiasson"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
